version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - apt-get update && apt-get -y --only-upgrade install ca-certificates
      - git config --global submodule.fetchJobs $((`nproc`-1))
      - ./update.sh
      - docker build --tag "ot3-image:latest" .
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - docker run --mount type=bind,src=${CODEBUILD_SRC_DIR},dst=/volumes/oe-core,consistency=delegated ot3-image:latest
  post_build:
    commands:
      - mkdir -p build/deploy/opentrons
      - find ./build/deploy/images -name "*opentrons-ot3-image-Tezi*" -exec cp {} build/deploy/opentrons/ot3-fullimage.tar \;
      - find ./build/deploy/images -name "ot3-system.zip" -exec cp {} build/deploy/opentrons \;
      - find ./build/deploy/images -name "VERSION.json" -exec cp {} build/deploy/opentrons \;
      - tar czf ./build/deploy/opentrons/buildstats.tar.gz ./build/tmp/buildstats
artifacts:
  base-directory: build/deploy
  files:
    - 'opentrons/*'
    - 'images/**/*'
  enable-symlinks: 'yes'

cache:
  paths:
    - 'downloads/**/*'
    - 'sstate-cache/**/*'
