version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - git config --global submodule.fetchJobs $((`nproc`-1))
      - git submodule update --init
      - docker build --build-arg "username=`whoami`" --build-arg "host_uid=`id -u`" --build-arg "host_gid=`id -g`" --tag "ot3-image:latest" .
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - docker run --mount type=bind,src=${CODEBUILD_SRC_DIR},dst=/home/ot3/oe-core,consistency=delegated ot3-image:latest

cache:
  paths:
    - build/tmp

artifacts:
  base-directory: build/deploy
  files:
    - '**/*'
  enable-symlinks: 'yes'
