version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - git config --global submodule.fetchJobs $((`nproc`-1))
      - ./update.sh
      - docker build --tag "ot3-image:latest" .
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - docker run --mount type=bind,src=${CODEBUILD_SRC_DIR},dst=/volumes/oe-core,consistency=delegated ot3-image:latest
artifacts:
  base-directory: build/deploy
  files:
    - 'opentrons/*'
    - 'images/**/*'
  enable-symlinks: 'yes'

cache:
  paths:
    - 'build/tmp/**/*'
    - 'build/cache/**/*'
    - 'build/downloads/**/*'
