version: 0.2

env:
  shell: bash

phases:
  pre_build:
    commands:
      - git config --global submodule.fetchJobs $((`nproc`-1))
      - ./update.sh
      - docker build --tag "ot3-image:latest" .
  build:
    commands:
      - echo ${CODEBUILD_SRC_DIR}
      - docker run --mount type=bind,src=${CODEBUILD_SRC_DIR},dst=/volumes/oe-core,consistency=delegated ot3-image:latest
  post_build:
    commands:
      - mkdir -p build/deploy/opentrons
      - D=build/deploy/images/verdin-imx8mm/ cp ${D}/$(find ${D} | grep Reference-Image-Minimal-Tezi | head -n 1) build/deploy/opentrons/toradex-minimal.tar
cache:
  paths:
    - downloads/**/*
artifacts:
  base-directory: build/deploy
  files:
    - 'opentrons/*'
    - 'images/**/*'
  enable-symlinks: 'yes'
