# See https://man.archlinux.org/man/iwd.config.5.en

[General]
AddressRandomization=disabled
RoamThreshold=-100
RoamThreshold5G=-100
CriticalRoamThreshold=-100
CriticalRoamThreshold5G=-100

[Blacklist]
InitialTimeout=1
InitialAccessPointBusyTimeout=30
Multiplier=30
MaximumTimeout=86400

[Scan]
DisableRoamingScan=false

[DriverQuirks]
PowerSaveDisable=*
