# Opentrons-robot-server directory user permissions, only for SCHEMA>=17
# Type  Path                                                                Mode  User  Group
z       /var/lib/opentrons-robot-server                                     0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/1[7-9]                              0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[2-9][0-9]                          0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[1-9][0-9][0-9]*                    0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/1[7-9]/protocols                    0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[2-9][0-9]/protocols                0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[1-9][0-9][0-9]*/protocols          0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/1[7-9]/protocols/*                  0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[2-9][0-9]/protocols/*              0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/[1-9][0-9][0-9]*/protocols/*        0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/1[7-9]/protocols/*/*.*              0644  root  ot-protocol
z       /var/lib/opentrons-robot-server/[2-9][0-9]/protocols/*/*.*          0644  root  ot-protocol
z       /var/lib/opentrons-robot-server/[1-9][0-9][0-9]*/protocols/*/*.*    0644  root  ot-protocol
z       /data/logs/sensor.log                                               0666  root  ot-protocol