# Type  Path                                                Mode  User  Group
z       /var/lib/opentrons-robot-server                     0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/*                   0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/*/protocols         0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/*/protocols/*       0755  root  ot-protocol
z       /var/lib/opentrons-robot-server/*/protocols/*/*.py  0755  root  ot-protocol