#!/bin/bash

# Disable compliance-ready software.

die() {
    echo "Failed: ${1}"
    exit 1
}

echo -n 'Password: '
read -rs password

serial=$(cat /var/serial)

[ "${password}" = "${serial}-0000" ] || die "Incorrect password"

echo "Exiting CRS"
systemctl stop opentrons-auth-server
systemctl stop opentrons-audit-server
rm -rf /var/lib/opentrons-auth-server
rm -rf /var/lib/opentrons-audit-server
echo "Rebooting"
reboot
