name: 'Simple Build Alert'
description: 'Sends Slack alerts for tagged build failures with clear links'

inputs:
  status:
    description: 'Build status: success, failure, or cancelled'
    required: true
  workflow_name:
    description: 'Name of the workflow'
    required: true
  failed_jobs:
    description: 'Comma-separated list of failed jobs (optional)'
    required: false
  channel_override:
    description: 'Override default channel (optional)'
    required: false
  tag_name:
    description: 'Tag name to display (optional, defaults to github.ref_name)'
    required: false
  webhook_url:
    description: 'Slack webhook URL'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Determine channel and webhook'
      id: channel-config
      shell: bash
      run: |
        # Use override if provided, otherwise default to release cycle
        if [[ -n "${{ inputs.channel_override }}" ]]; then
          echo "channel=${{ inputs.channel_override }}" >> $GITHUB_OUTPUT
          echo "webhook_secret=OT_APP_RELEASE_SLACK_NOTIFICATION_WEBHOOK_URL" >> $GITHUB_OUTPUT
        else
          # All tagged builds go to release cycle by default
          echo "channel=#release-cycle" >> $GITHUB_OUTPUT
          echo "webhook_secret=OT_APP_RELEASE_SLACK_NOTIFICATION_WEBHOOK_URL" >> $GITHUB_OUTPUT
        fi

    - name: 'Send Slack Alert'
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook-type: 'incoming-webhook'
        payload: |
          {
            "channel": "${{ steps.channel-config.outputs.channel }}",
            "username": "GitHub Actions",
            "icon_emoji": ":robot_face:",
            "attachments": [
              {
                "color": "${{ inputs.status == 'success' && 'good' || inputs.status == 'failure' && 'danger' || 'warning' }}",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "${{ inputs.status == 'success' && '✅ Build Success' || inputs.status == 'failure' && '❌ Build Failed' || '⚠️ Build Cancelled' }}"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Tag:* `${{ inputs.tag_name || github.ref_name }}`"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Workflow:* `${{ inputs.workflow_name }}`"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Status:* `${{ inputs.status }}`"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*View Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Open Workflow>"
                      }
                      ${{ inputs.failed_jobs && format(',{{ "type": "mrkdwn", "text": "*Failed Jobs:* `{0}`" }}', inputs.failed_jobs) || '' }}
                    ]
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
