name: 'Simple Build Alert'
description: 'Sends Slack alerts for tagged build failures with clear links'

inputs:
  status:
    description: 'Build status: success, failure, or cancelled'
    required: true
  workflow_name:
    description: 'Name of the workflow'
    required: true
  failed_jobs:
    description: 'Comma-separated list of failed jobs (optional)'
    required: false
  webhook_url:
    description: 'Slack webhook URL'
    required: true
  console_url:
    description: 'S3 console URL (optional)'
    required: false
  system_url:
    description: 'System update zip URL (optional)'
    required: false
  fullimage_url:
    description: 'Full image zip URL (optional)'
    required: false
  version_file_url:
    description: 'Version file URL (optional)'
    required: false
  release_notes_file_url:
    description: 'Release notes file URL (optional)'
    required: false
  oe-core_ref:
    description: 'oe-core ref (optional)'
    required: false
  monorepo_ref:
    description: 'Monorepo ref (optional)'
    required: false
  firmware_ref:
    description: 'Firmware ref (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Extract tag name'
      id: tag-name
      shell: bash
      run: |
        # Extract tag name from monorepo_ref if provided, otherwise use github.ref_name
        if [[ -n "${{ inputs.monorepo_ref }}" ]]; then
          tag_ref="${{ inputs.monorepo_ref }}"
          # Remove refs/tags/ or refs/heads/ prefix if present
          tag_name="${tag_ref#refs/tags/}"
          tag_name="${tag_name#refs/heads/}"
        else
          tag_name="${{ github.ref_name }}"
        fi
        echo "tag=${tag_name}" >> $GITHUB_OUTPUT

    - name: 'Build payload'
      id: build-payload
      shell: bash
      run: |
        # Use Python script to build JSON payload properly
        # The script is in the same directory as action.yml
        payload_json=$(python3 build_payload.py)
        
        # Write to GITHUB_OUTPUT using multiline format
        {
          echo "payload<<EOF"
          echo "$payload_json"
          echo "EOF"
        } >> $GITHUB_OUTPUT
      working-directory: ${{ github.action_path }}
      env:
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_WORKFLOW_NAME: ${{ inputs.workflow_name }}
        TAG_NAME: ${{ steps.tag-name.outputs.tag }}
        INPUT_FAILED_JOBS: ${{ inputs.failed_jobs }}
        INPUT_OE_CORE_REF: ${{ inputs.oe-core_ref }}
        INPUT_MONOREPO_REF: ${{ inputs.monorepo_ref }}
        INPUT_FIRMWARE_REF: ${{ inputs.firmware_ref }}
        INPUT_CONSOLE_URL: ${{ inputs.console_url }}
        INPUT_SYSTEM_URL: ${{ inputs.system_url }}
        INPUT_FULLIMAGE_URL: ${{ inputs.fullimage_url }}
        INPUT_VERSION_FILE_URL: ${{ inputs.version_file_url }}
        INPUT_RELEASE_NOTES_FILE_URL: ${{ inputs.release_notes_file_url }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}

    - name: 'Send Slack Alert'
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook-type: 'incoming-webhook'
        payload: ${{ steps.build-payload.outputs.payload }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
      continue-on-error: false
