name: 'Simple Build Alert'
description: 'Sends Slack alerts for tagged build failures with clear links'

inputs:
  status:
    description: 'Build status: success, failure, or cancelled'
    required: true
  workflow_name:
    description: 'Name of the workflow'
    required: true
  failed_jobs:
    description: 'Comma-separated list of failed jobs (optional)'
    required: false
  webhook_url:
    description: 'Slack webhook URL'
    required: true
  console_url:
    description: 'S3 console URL (optional)'
    required: false
  system_url:
    description: 'System update zip URL (optional)'
    required: false
  fullimage_url:
    description: 'Full image zip URL (optional)'
    required: false
  version_file_url:
    description: 'Version file URL (optional)'
    required: false
  release_notes_file_url:
    description: 'Release notes file URL (optional)'
    required: false
  oe-core_ref:
    description: 'oe-core ref (optional)'
    required: false
  monorepo_ref:
    description: 'Monorepo ref (optional)'
    required: false
  firmware_ref:
    description: 'Firmware ref (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Prepare refs for payload'
      id: prepare-refs
      shell: bash
      run: |
        # Strip refs/tags/ or refs/heads/ prefix from refs
        oe_core_display="${{ inputs.oe-core_ref }}"
        oe_core_display="${oe_core_display#refs/tags/}"
        oe_core_display="${oe_core_display#refs/heads/}"
        echo "oe-core=${oe_core_display}" >> $GITHUB_OUTPUT
        
        monorepo_display="${{ inputs.monorepo_ref }}"
        monorepo_display="${monorepo_display#refs/tags/}"
        monorepo_display="${monorepo_display#refs/heads/}"
        echo "monorepo=${monorepo_display}" >> $GITHUB_OUTPUT
        
        firmware_display="${{ inputs.firmware_ref }}"
        firmware_display="${firmware_display#refs/tags/}"
        firmware_display="${firmware_display#refs/heads/}"
        echo "firmware=${firmware_display}" >> $GITHUB_OUTPUT
        
        # Determine type
        if [[ "${{ inputs.monorepo_ref }}" == refs/tags/* ]]; then
          echo "ref_type=tag" >> $GITHUB_OUTPUT
        else
          echo "ref_type=branch" >> $GITHUB_OUTPUT
        fi

    - name: 'Send Slack Alert'
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook: ${{ inputs.webhook_url }}
        webhook-type: incoming-webhook
        payload: "{\"s3-url\":\"${{ inputs.console_url }}/\",\"type\":\"${{ steps.prepare-refs.outputs.ref_type }}\",\"reflike\":\"${{ steps.prepare-refs.outputs.oe-core }}\",\"monorepo-reflike\":\"${{ steps.prepare-refs.outputs.monorepo }}\",\"firmware-reflike\":\"${{ steps.prepare-refs.outputs.firmware }}\",\"full-image\":\"${{ inputs.fullimage_url }}\",\"system-update\":\"${{ inputs.system_url }}\",\"version-file\":\"${{ inputs.version_file_url }}\",\"release-notes\":\"${{ inputs.release_notes_file_url }}\"}"
      continue-on-error: false
