name: 'Simple Build Alert'
description: 'Sends Slack alerts for tagged build failures with clear links'

inputs:
  status:
    description: 'Build status: success, failure, or cancelled'
    required: true
  workflow_name:
    description: 'Name of the workflow'
    required: true
  failed_jobs:
    description: 'Comma-separated list of failed jobs (optional)'
    required: false
  channel_override:
    description: 'Override default channel (optional)'
    required: false
  webhook_url:
    description: 'Slack webhook URL'
    required: true
  console_url:
    description: 'S3 console URL (optional)'
    required: false
  system_url:
    description: 'System update zip URL (optional)'
    required: false
  fullimage_url:
    description: 'Full image zip URL (optional)'
    required: false
  version_file_url:
    description: 'Version file URL (optional)'
    required: false
  release_notes_file_url:
    description: 'Release notes file URL (optional)'
    required: false
  oe-core_ref:
    description: 'oe-core ref (optional)'
    required: false
  monorepo_ref:
    description: 'Monorepo ref (optional)'
    required: false
  firmware_ref:
    description: 'Firmware ref (optional)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Determine channel and webhook'
      id: channel-config
      shell: bash
      run: |
        # Use override if provided, otherwise default to release cycle
        if [[ -n "${{ inputs.channel_override }}" ]]; then
          echo "channel=${{ inputs.channel_override }}" >> $GITHUB_OUTPUT
          echo "webhook_secret=OT_APP_RELEASE_SLACK_NOTIFICATION_WEBHOOK_URL" >> $GITHUB_OUTPUT
        else
          # All tagged builds go to release cycle by default
          echo "channel=#release-cycle" >> $GITHUB_OUTPUT
          echo "webhook_secret=OT_APP_RELEASE_SLACK_NOTIFICATION_WEBHOOK_URL" >> $GITHUB_OUTPUT
        fi

    - name: 'Extract tag name'
      id: tag-name
      shell: bash
      run: |
        # Extract tag name from monorepo_ref if provided, otherwise use github.ref_name
        if [[ -n "${{ inputs.monorepo_ref }}" ]]; then
          tag_ref="${{ inputs.monorepo_ref }}"
          # Remove refs/tags/ prefix if present
          tag_name="${tag_ref#refs/tags/}"
        else
          tag_name="${{ github.ref_name }}"
        fi
        echo "tag=${tag_name}" >> $GITHUB_OUTPUT

    - name: 'Build payload'
      id: build-payload
      shell: bash
      run: |
        # Use Python to build JSON payload properly
        payload_json=$(python3 << 'PYTHON_SCRIPT'
        import json
        import os
        
        # Get inputs
        status = os.environ.get('INPUT_STATUS', '')
        workflow_name = os.environ.get('INPUT_WORKFLOW_NAME', '')
        tag_name = os.environ.get('TAG_NAME', '')
        failed_jobs = os.environ.get('INPUT_FAILED_JOBS', '')
        oe_core_ref = os.environ.get('INPUT_OE_CORE_REF', '')
        monorepo_ref = os.environ.get('INPUT_MONOREPO_REF', '')
        firmware_ref = os.environ.get('INPUT_FIRMWARE_REF', '')
        console_url = os.environ.get('INPUT_CONSOLE_URL', '')
        system_url = os.environ.get('INPUT_SYSTEM_URL', '')
        fullimage_url = os.environ.get('INPUT_FULLIMAGE_URL', '')
        version_file_url = os.environ.get('INPUT_VERSION_FILE_URL', '')
        release_notes_file_url = os.environ.get('INPUT_RELEASE_NOTES_FILE_URL', '')
        channel = os.environ.get('CHANNEL', '#release-cycle')
        github_server_url = os.environ.get('GITHUB_SERVER_URL', '')
        github_repository = os.environ.get('GITHUB_REPOSITORY', '')
        github_run_id = os.environ.get('GITHUB_RUN_ID', '')
        
        # Build status text and color
        if status == 'success':
            status_text = '✅ Build Success'
            color = 'good'
        elif status == 'failure':
            status_text = '❌ Build Failed'
            color = 'danger'
        else:
            status_text = '⚠️ Build Cancelled'
            color = 'warning'
        
        # Build fields array
        fields = [
            {"type": "mrkdwn", "text": f"*Tag:* `{tag_name}`"},
            {"type": "mrkdwn", "text": f"*Workflow:* `{workflow_name}`"},
            {"type": "mrkdwn", "text": f"*Status:* `{status}`"},
            {"type": "mrkdwn", "text": f"*View Details:* <{github_server_url}/{github_repository}/actions/runs/{github_run_id}|Open Workflow>"}
        ]
        
        if failed_jobs:
            fields.append({"type": "mrkdwn", "text": f"*Failed Jobs:* `{failed_jobs}`"})
        
        if oe_core_ref:
            fields.append({"type": "mrkdwn", "text": f"*oe-core:* `{oe_core_ref}`"})
        
        if monorepo_ref:
            fields.append({"type": "mrkdwn", "text": f"*Monorepo:* `{monorepo_ref}`"})
        
        if firmware_ref:
            fields.append({"type": "mrkdwn", "text": f"*Firmware:* `{firmware_ref}`"})
        
        # Build blocks array
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": status_text
                }
            },
            {
                "type": "section",
                "fields": fields
            }
        ]
        
        # Add artifacts section if URLs are provided
        if console_url or system_url or fullimage_url or version_file_url or release_notes_file_url:
            artifacts_lines = ["*Artifacts:*"]
            
            if console_url:
                artifacts_lines.append(f"*Download at:* <{console_url}|S3 Console>")
            
            if system_url:
                artifacts_lines.append(f"*System Image (For Updates):* <{system_url}|Download>")
            
            if fullimage_url:
                artifacts_lines.append(f"*Full Image (For Flashing):* <{fullimage_url}|Download>")
            
            if version_file_url:
                artifacts_lines.append(f"*Version file:* <{version_file_url}|Download>")
            
            if release_notes_file_url:
                artifacts_lines.append(f"*Release notes:* <{release_notes_file_url}|Download>")
            
            artifacts_text = "\n".join(artifacts_lines)
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": artifacts_text
                }
            })
        
        # Build full payload
        payload = {
            "channel": channel,
            "username": "GitHub Actions",
            "icon_emoji": ":robot_face:",
            "attachments": [
                {
                    "color": color,
                    "blocks": blocks
                }
            ]
        }
        
        # Output JSON
        print(json.dumps(payload))
        PYTHON_SCRIPT
        )
        
        # Write to GITHUB_OUTPUT using multiline format
        {
          echo "payload<<EOF"
          echo "$payload_json"
          echo "EOF"
        } >> $GITHUB_OUTPUT
      env:
        INPUT_STATUS: ${{ inputs.status }}
        INPUT_WORKFLOW_NAME: ${{ inputs.workflow_name }}
        TAG_NAME: ${{ steps.tag-name.outputs.tag }}
        INPUT_FAILED_JOBS: ${{ inputs.failed_jobs }}
        INPUT_OE_CORE_REF: ${{ inputs.oe-core_ref }}
        INPUT_MONOREPO_REF: ${{ inputs.monorepo_ref }}
        INPUT_FIRMWARE_REF: ${{ inputs.firmware_ref }}
        INPUT_CONSOLE_URL: ${{ inputs.console_url }}
        INPUT_SYSTEM_URL: ${{ inputs.system_url }}
        INPUT_FULLIMAGE_URL: ${{ inputs.fullimage_url }}
        INPUT_VERSION_FILE_URL: ${{ inputs.version_file_url }}
        INPUT_RELEASE_NOTES_FILE_URL: ${{ inputs.release_notes_file_url }}
        CHANNEL: ${{ steps.channel-config.outputs.channel }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}

    - name: 'Send Slack Alert'
      uses: slackapi/slack-github-action@v2.1.1
      with:
        webhook-type: 'incoming-webhook'
        payload: ${{ steps.build-payload.outputs.payload }}
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.webhook_url }}
