name: 'Start an OT3 image build on a git branch'
run-name: 'Starting a branch build of OT3 software for ${{ github.ref_name }}'

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build-required:
    name: 'Determine if build is already queued'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Get queued jobs'
        uses: octokit/request-action@v2.x
        id: get_queued_runs
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          route: GET /repos/{owner}/{repo}/actions/runs?status=queued
          owner: opentrons
          repo: oe-core
      - name: 'Get data of queued jobs'


      - run: "echo queued runs: '${{ steps.get_queued_runs.outputs.data }}'"
