name: 'Start a Flex image build on a git branch'
run-name: 'Starting a branch build of Flex for ${{ github.ref_name }}'

on:
  push:
    branches:
      - 'main'
  pull_request:


jobs:
  start-build:
    name: 'starting a build for branch ${{ github.ref }}'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'start build'
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow-id}/dispatches
          owner: opentrons
          repo: oe-core
          workflow-id: build-ot3-actions.yml
          ref: ${{github.ref}}
          inputs: |
            {
              "oe-core-ref": "${{ github.ref }}",
              "monorepo-ref": "-",
              "infra-stage": "stage-prod"
            }
