name: 'Build OT3 image on github workflows'

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  run-build:
    name: 'Building images'
    timeout-minutes: 360
    runs-on: 'self-hosted'
    steps:
      - name: Fetch sources
        uses: 'actions/checkout@v3'
        with:
          submodules: true
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build container
        run: |
          tmp_dir=$(mktemp -d -t ci-XXXXXXX)
          cp start.sh $tmp_dir/
          docker build -f ./Dockerfile --tag "ot3-image:latest" $tmp_dir
      - name: Extract download cache
        uses: actions/cache@v3
        with:
          path: downloads/**/*
          key: downloads-${{ github.run_id }}
          restore-keys: |
            downloads
      - name: Download sources
        run: |
          docker run --rm --mount type=bind,src=$(pwd),dst=/volumes/oe-core,consistency=delegated ot3-image:latest opentrons-ot3-image --runall=fetch
      - name: Build image
        run: |
          docker run --rm --mount type=bind,src=$(pwd),dst=/volumes/oe-core,consistency=delegated ot3-image:latest
      - name: Prune images
        if: always()
        run: docker image prune -af
      - name: Gather results
        run: |
          mkdir -p build/deploy/opentrons
          find ./build/deploy/images -name "*opentrons-ot3-image-Tezi*" -exec cp {} build/deploy/opentrons/opentrons-image.tar \;
          find ./build/deploy/images -name opentrons-ot3-image-verdin-imx8mm.wic.bmap -exec cp {} build/deploy/opentrons \;
          find ./build/deploy/images -name opentrons-ot3-image-verdin-imx8mm.wic.gz -exec cp {} build/deploy/opentrons \;
          tar czf ./build/deploy/opentrons/buildstats.tar.gz ./build/tmp/buildstats
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: opentrons-image
          path: build/deploy/opentrons/**/*
